### ISSUE TITLE
Add alt-text tags to Android usage pages

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#60]
Add alt-text tags to the Android usage pages at https://wildaid.github.io/useAndroid/ (there are only 2 right now). 

Pages exists at: https://wildaid.github.io/useAndroid/
In the code at:
_posts/use/2020-07-01-LoginA.md
_posts/use/2020-07-01-HomeScreenA.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by gabrielhicks** [comment]
I would love to work on this and improve my alt tag abilities!

Thanks!

**Comment by Sheeri** [comment]
Hello @gabrielhicks, thanks for offering to work on this! I have assigned it to you. The guide in the description has a few examples, and links to 2 web pages that have much more inspiration. Happy coding!

**Comment by gabrielhicks** [comment]
Hi! I am curious if the pull requests made will be valid for hacktoberfest, or if they must inclide a hacktoberfest-accepted tag?
