### ISSUE TITLE
Add alt-text tags to iOS usage pages

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#61]
Add alt-text tags to the iOS usage pages at https://wildaid.github.io/useiOS/ (there are only 3 right now). 

Page exists at: https://wildaid.github.io/useiOS/
In the code at: 
_posts/use/2020-08-01-LoginI.md
_posts/use/2020-08-01-HomeScreenI.md
_posts/use/2020-08-13-FeedbackI.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by kandarppatel28** [comment]
Hi @o-fish-wildaid , I have gone through the requirement and would like to work on it, please assign this to me, Thank you.

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.
