### ISSUE TITLE
Add alt-text tags to foundation pages (0-3)

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#62]
Add alt-text tags to the build foundation pages (0-3). 

In the code at: 
_posts/build_fdn/2020-06-09-Atlas-Database.md 
_posts/build_fdn/2020-06-09-Atlas-Database-config.md 
_posts/build_fdn/2020-06-09-Data-Import.md
_posts/build_fdn/2020-06-09-Create-Realm.md

On the web at: 
https://wildaid.github.io/foundation/2020/06/09/Atlas-Database.html
https://wildaid.github.io/foundation/2020/06/09/Atlas-Database-config.html
https://wildaid.github.io/foundation/2020/06/09/Data-Import.html
https://wildaid.github.io/foundation/2020/06/09/Create-Realm.html

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by Roshanpaswan** [comment]
i would like to work on it

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.
