### ISSUE TITLE
Add alt-text tags to foundation pages (4-7)

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#63]
Add alt-text tags to the build foundation pages (4-7). 

In the code at: 
_posts/build_fdn/2020-06-09-Realm-API-Key.md
_posts/build_fdn/2020-06-09-Setup-Commandline-for-Realm-Import.md
_posts/build_fdn/2020-06-09-Import-Realm-Code.md
_posts/build_fdn/2020-06-09-Connect-Realm-With-Data.md

On the web at:
https://wildaid.github.io/foundation/2020/06/09/Realm-API-Key.html
https://wildaid.github.io/foundation/2020/06/09/Setup-Commandline-for-Realm-Import.html
https://wildaid.github.io/foundation/2020/06/09/Import-Realm-Code.html
https://wildaid.github.io/foundation/2020/06/09/Connect-Realm-With-Data.html

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by ericblancas23** [comment]
I can add in these alt tags, assign to me and I'll fork over the repo

**Comment by Sheeri** [comment]
Hello @ericblancas23, thanks for offering to work on this! I have assigned it to you.
