### ISSUE TITLE
Add alt-text tags to web build pages

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#64]
Add alt-text tags to the web build pages (there are 3 of them). 

In the code at: _posts/build_web/
Pages on the web are:
https://wildaid.github.io/web/2020/06/09/Prepare-Web-App.html
https://wildaid.github.io/web/2020/06/09/Build-Web-App.html
https://wildaid.github.io/web/2020/06/09/Test-Web-App.html

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by aayushi2883** [comment]
i would like to work on this

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.

**Comment by ishitacodes** [comment]
I would like to work on this issue.

**Comment by Sheeri** [comment]
Hi @ishitacodes - this issue is already assigned; there are similar issues at https://github.com/WildAid/wildaid.github.io/issues if you want to try one of those.

**Comment by aayushi2883** [comment]
Thanks @Sheeri , but could you explain a bit more about this issue please

**Comment by aayushi2883** [comment]
[](https://github.com/WildAid/wildaid.github.io/pull/78#issue-497220220) this is a link to the PR i have made

**Comment by aayushi2883** [comment]
[PR](https://github.com/WildAid/wildaid.github.io/pull/78#issue-497220220) this is a link to the PR i have made
