### ISSUE TITLE
Add alt-text tags to post-chart build pages

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#65]
Add alt-text tags to the troubleshooting page:

Page exists at: https://wildaid.github.io/charts/2020/06/14/TroubleshootingCharts.html
In the code at: _posts/build_charts/2020-06-14-TroubleshootingCharts.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by jessicasalbert** [comment]
Hey, I've read the guidelines and would love to work on this issue if you could to assign it to me. Thanks!

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you @jessicasalbert
