### ISSUE TITLE
Add alt-text tags to build charts overview and deploy pages

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#66]
Add alt-text tags to the build charts overview and the build and deploy to test charts pages.

Build charts overview:
Page exists at: https://wildaid.github.io/charts/2020/06/11/Build-Charts.html
In the code at: _posts/build_charts/2020-06-11-Build-Charts.md

Build and Deploy to Test, first time
Page exists at: https://wildaid.github.io/charts/2020/06/12/Test-Charts.html
In the code at: _posts/build_charts/2020-06-12-Test-Charts.md

Build and Deploy to Test, generic
Page exists at: https://wildaid.github.io/charts/2020/06/14/Test-Charts.html
In the code at: _posts/build_charts/2020-06-14-Test-Charts.md

 A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by ericblancas23** [comment]
I can add in these alt tags

**Comment by Sheeri** [comment]
Hi @ericblancas23 - thanks for expressing interest in this issue. Since you have been assigned another issue and haven't submitted a PR for it yet, we ask that you finish that issue first, before we assign another issue to you.

**Comment by wlcreate** [comment]
Hi! Can I be assigned to this issue?

**Comment by Sheeri** [comment]
Hello @wlcreate, thanks for offering to work on this! I have assigned it to you.
