### ISSUE TITLE
Add alt-text tags to Charts Setup page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#67]
Add alt-text tags to the Charts Setup page. 

Page exists at: https://wildaid.github.io/charts/2020/06/12/Charts-Setup.html
In the code at: _posts/build_charts/2020-06-12-Charts-Setup.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by RuchaYagnik** [comment]
Hi @o-fish-wildaid, I have gone through the issue requisite and would like to contribute to it. I request to assign this issue to me, Thank you.

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

The PR for this issue is great and has been merged into the code. Thanks so much for contributing, we really appreciate your effort!

**Comment by RuchaYagnik** [comment]
Glad to be able to work on it, Thank you for giving the opportunity :) 😊
