### ISSUE TITLE
Add alt-text tags to Embed Boarding List Chart page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#69]
Add alt-text tags to the Embed Boarding List Chart page. 

Page exists at: https://wildaid.github.io/charts/2020/06/12/Embed-Boardings-List.html
In the code at: _posts/build_charts/2020-06-12-Embed-Boardings-List.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by RuchaYagnik** [comment]
Hi @o-fish-wildaid, I have gone through the issue requisite and would like to contribute to it. I request to assign this issue to me, Thank you.

**Comment by Sheeri** [comment]
Hello! Thanks for expressing interest in this issue. Since you have been assigned issue #67 and haven't submitted a PR for it yet, we ask that you finish that issue first, before we assign another issue to you.

**Comment by GabbyJ** [comment]
Hi @Sheeri, I would like to work on this issue. Can you assign it to me?

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.
