### ISSUE TITLE
Add alt-text tags to Create Compliance Charts - Numbers page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#70]
Add alt-text tags to the Create Compliance Charts - Numbers page. 

Page exists at: https://wildaid.github.io/charts/2020/06/12/Create-Compliance.html
In the code at: _posts/build_charts/2020-06-12-Create-Compliance.md 

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by RuchaYagnik** [comment]
Hi @o-fish-wildaid, I have gone through the issue requisite and would like to contribute to it. I request to assign this issue to me, Thank you.

**Comment by Sheeri** [comment]
Hello! Thanks for expressing interest in this issue. Since you have been assigned issue #67 and haven't submitted a PR for it yet, we ask that you finish that issue first, before we assign another issue to you.

**Comment by RuchaYagnik** [comment]
Hi @Sheeri! as mentioned by you earlier, I have submitted a PR for issue #68. Can I be assigned this issue once the PR for issue #68  is reviewed ?

**Comment by Sheeri** [comment]
@RuchaYagnik I have assigned this issue to you.
