### ISSUE TITLE
Add alt-text tags to Create Compliance Charts - Percentage page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#71]
Add alt-text tags to the Create Compliance Charts - Percentage page.

Page exists at: https://wildaid.github.io/charts/2020/06/12/Create-Compliance2.html
In the code at: _posts/build_charts/2020-06-12-Create-Compliance2.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by kandarppatel28** [comment]
Hi @o-fish-wildaid , I have gone through the requirement and would like to work on it, please assign this to me, Thank you.

**Comment by Sheeri** [comment]
Hi there, you already have #72 assigned to you. Please complete that issue first and then we can see about assigning this to you, if nobody else wants it before then.

**Comment by gabrielhicks** [comment]
Hello @o-fish-wildaid ! 

I would like to work on this issue if you wouldn't mind assigning it to me.

Thanks!

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.

**Comment by gabrielhicks** [comment]
Hi! I am curious if the pull requests made will be valid for hacktoberfest, or if they must inclide a hacktoberfest-accepted tag?

**Comment by Sheeri** [comment]
Hi @gabrielhicks - The guidelines at https://hacktoberfest.digitalocean.com/details say:

"Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted."

This repo has the hacktoberfest topic, so once the pull request has been merged or approved, it will count towards your participation. The 'hacktoberfest-accepted' tag is not necessary, as this repo has the 'hacktoberfest' topic.

If you want to track your progress, you can login to your hacktoberfest profile page at https://hacktoberfest.digitalocean.com/profile

Here's what mine currently looks like:
![Screen Shot 2020-10-07 at 12 44 36 PM](https://user-images.githubusercontent.com/1767528/95361544-dcf59580-089a-11eb-9cc7-c51830f3df1b.png)

The clock on the left and the "Mature in" at the right show that once the 14-day waiting period is over, my PRs will count towards hacktoberfest participation. 

Here's the legend on the page:
![Screen Shot 2020-10-07 at 12 46 10 PM](https://user-images.githubusercontent.com/1767528/95361711-14fcd880-089b-11eb-950f-b04bbad0ece1.png)

So if you have any doubts or worries about ANY pull request - in this repo or any other - you can check your status.

**Comment by gabrielhicks** [comment]
Thank you!!!
