### ISSUE TITLE
Add alt-text tags to Create Compliance Charts - Donut page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#72]
Add alt-text tags to the Create Compliance Charts - Donut page. 

Page exists at: https://wildaid.github.io/charts/2020/06/12/Create-Compliance-Donut.html
In the code at: _posts/build_charts/2020-06-12-Create-Compliance-Donut.md 

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by kandarppatel28** [comment]
Hi @o-fish-wildaid , I have gone through the requirement and would like to work on it, please assign this to me, Thank you.

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you.
