### ISSUE TITLE
Add alt-text tags to the Create Map page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/wildaid.github.io#73]
Add alt-text tags to the Create Map page. 

Page exists at: https://wildaid.github.io/charts/2020/06/13/Create-Map.html
In the code at: _posts/build_charts/2020-06-13-Create-Map.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

**Comment by mantasio** [comment]
I can help with that

**Comment by Sheeri** [comment]
@mantasio I have assigned this to you.

**Comment by aayushi2883** [comment]
If this issue is open, can i work on it?

**Comment by Sheeri** [comment]
Hi @aayushi2883 - this issue is still open. I have unassigned mantasio for having no information for over 3 days, and have assigned it to you. Thanks for offering to work on it!

**Comment by mantasio** [comment]
Sorry, just couldn’t find free time to turn on my laptop. Thanks and good luck @aayushi2883 !

**Comment by Augs0** [comment]
Hey is this issue still open? Happy to work on this and get going right away :)

**Comment by aayushi2883** [comment]
@Sheeri, "This branch is 35 commits behind" how do I solve this?

**Comment by Sheeri** [comment]
Hello @Augs0, thanks for offering to work on this! I have assigned it to you.

**Comment by Sheeri** [comment]
Hi @aayushi2883 - you can resolve that by doing a 'git pull'.

However, @Augs0 asked to work on this, and it has been more than the 3 days we ask for keepalives in our [contribution guide](https://wildaid.github.io/contribute/index.html) so I have assigned it to them.
